# Use if you need a npm auth token for private packages.
#secrets:
#  NPM_AUTH_TOKEN:
#    environment: NPM_AUTH_TOKEN

services:
  database:
    container_name: database
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=UTC # Set the timezone to UTC
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=en_US.UTF-8 # Set character encoding to UTF-8
    ports:
      - '5432:5432'
    volumes:
      - ./apps/database/data:/var/lib/postgresql/data
      - ./apps/database/src/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  database-migrator:
    container_name: database-migrator
    build:
      context: .
      dockerfile: apps/database-migrator/.ci/Dockerfile
    volumes:
      - ./apps/database/migrations:/app/migrations
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_SERVER=database

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: apps/backend/.ci/Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      database-migrator:
        condition: service_completed_successfully
    environment:
      - DB_SERVER=database

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/frontend/.ci/Dockerfile
    # This is how you would inject the secret auth token.
    #      secrets:
    #        - NPM_AUTH_TOKEN
    ports:
      - '3000:3000'
    depends_on:
      database-migrator:
        condition: service_completed_successfully

  test-api:
    container_name: test-api
    build:
      context: .
      dockerfile: apps/test-api/.ci/Dockerfile
    depends_on:
      - backend
    environment:
      BASE_TEST_URL: 'http://backend:3001'

  test-e2e:
    container_name: test-e2e
    network_mode: host
    build:
      context: .
      dockerfile: apps/test-e2e/.ci/Dockerfile
    volumes:
      - ./apps/test-e2e/playwright:/app/apps/test-e2e/playwright
      - ./apps/test-e2e/test-results:/app/apps/test-e2e/test-results
    env_file: apps/test-e2e/.env
    depends_on:
      - frontend
